ALTER TABLE `floor` CHANGE `BID` `BKID` INT(11) NOT NULL;
ALTER TABLE `room` CHANGE `BID` `BKID` INT(11) NOT NULL;
ALTER TABLE `floor` ADD `BID` INT(11) NOT NULL AFTER `OrgID`;
ALTER TABLE `room` ADD `BID` INT(11) NOT NULL AFTER `OrgID`;

